name: main
on: [push]
jobs:
  codecheck:
    runs-on: ubuntu-latest
    steps:
      - name: python-flake8
        # You may pin to the exact commit or the version.
        # uses: julianwachholz/flake8-action@75749239077651dfd0ecbe405899cdcb0673ee8f
        uses: julianwachholz/flake8-action@v2.0.2
